"""Updated models

Revision ID: d4d96b56e50d
Revises: 76813d529bc0
Create Date: 2025-03-22 08:42:02.815242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4d96b56e50d'
down_revision: Union[str, None] = '76813d529bc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('contact_details_email_key', 'contact_details', type_='unique')
    op.alter_column('experiences', 'on_going',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index('ix_resume_files_user_id', table_name='resume_files')
    op.create_index(op.f('ix_resume_files_user_id'), 'resume_files', ['user_id'], unique=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=60),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_index(op.f('ix_resume_files_user_id'), table_name='resume_files')
    op.create_index('ix_resume_files_user_id', 'resume_files', ['user_id'], unique=True)
    op.alter_column('experiences', 'on_going',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_unique_constraint('contact_details_email_key', 'contact_details', ['email'])
    # ### end Alembic commands ###
